/**
 * Autogenerated by Thrift Compiler (0.12.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package org.pismery.demo.netty.thrift.generate;


@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.12.0)", date = "2019-09-16")
public enum RequestType implements org.apache.thrift.TEnum {
  GET(0),
  POST(1),
  PUT(2),
  DELETE(3);

  private final int value;

  private RequestType(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  @org.apache.thrift.annotation.Nullable
  public static RequestType findByValue(int value) { 
    switch (value) {
      case 0:
        return GET;
      case 1:
        return POST;
      case 2:
        return PUT;
      case 3:
        return DELETE;
      default:
        return null;
    }
  }
}
