/**
 * Autogenerated by Thrift Compiler (0.12.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package org.pismery.demo.netty.thrift.generate;


@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.12.0)", date = "2019-09-16")
public enum ResponseType implements org.apache.thrift.TEnum {
  SUCCESS(0),
  FAILURE(-1);

  private final int value;

  private ResponseType(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  @org.apache.thrift.annotation.Nullable
  public static ResponseType findByValue(int value) { 
    switch (value) {
      case 0:
        return SUCCESS;
      case -1:
        return FAILURE;
      default:
        return null;
    }
  }
}
